service:
  name: thingtalk-service

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

package:
  include:
    - ./thingpedia.tt

functions:
  convert:
    handler: src/handler.convert
    events:
      - http:
          method: get
          path: convert
